# Generated by Django 3.0 on 2019-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(default='', max_length=255)),
                ('waktu_publikasi', models.DateTimeField(verbose_name='Waktu Tayang')),
                ('jumlah_komentar', models.IntegerField(default=0)),
                ('judul_post', models.CharField(default='', max_length=255)),
                ('konten', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='', max_length=255)),
                ('foto', models.CharField(default='', max_length=255)),
                ('testimoni', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='', max_length=255)),
                ('foto', models.CharField(default='', max_length=255)),
                ('pengalaman', models.TextField(default='')),
                ('testimoni', models.TextField(default='')),
            ],
        ),
    ]
