# Generated by Django 3.0 on 2019-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphatech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='waktu_publikasi',
            field=models.DateField(verbose_name='Waktu Tayang'),
        ),
    ]
